version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - appnet
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/home/webuser/.ssh
    ports:
      - "8080:8080"
    container_name: app
networks:
  appnet:
    driver: bridge